//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/InputSystem/ADVInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ADVInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ADVInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ADVInput"",
    ""maps"": [
        {
            ""name"": ""Window"",
            ""id"": ""3db1a50a-d8de-4fc7-8ef9-5414c10dd6fb"",
            ""actions"": [
                {
                    ""name"": ""SwitchEnable"",
                    ""type"": ""Button"",
                    ""id"": ""4d849828-feae-4e49-95b1-a430b883162e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7bb064ff-329d-4049-bc60-44328aef330e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchEnable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Window
        m_Window = asset.FindActionMap("Window", throwIfNotFound: true);
        m_Window_SwitchEnable = m_Window.FindAction("SwitchEnable", throwIfNotFound: true);
    }

    ~@ADVInput()
    {
        UnityEngine.Debug.Assert(!m_Window.enabled, "This will cause a leak and performance issues, ADVInput.Window.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Window
    private readonly InputActionMap m_Window;
    private List<IWindowActions> m_WindowActionsCallbackInterfaces = new List<IWindowActions>();
    private readonly InputAction m_Window_SwitchEnable;
    public struct WindowActions
    {
        private @ADVInput m_Wrapper;
        public WindowActions(@ADVInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchEnable => m_Wrapper.m_Window_SwitchEnable;
        public InputActionMap Get() { return m_Wrapper.m_Window; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WindowActions set) { return set.Get(); }
        public void AddCallbacks(IWindowActions instance)
        {
            if (instance == null || m_Wrapper.m_WindowActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WindowActionsCallbackInterfaces.Add(instance);
            @SwitchEnable.started += instance.OnSwitchEnable;
            @SwitchEnable.performed += instance.OnSwitchEnable;
            @SwitchEnable.canceled += instance.OnSwitchEnable;
        }

        private void UnregisterCallbacks(IWindowActions instance)
        {
            @SwitchEnable.started -= instance.OnSwitchEnable;
            @SwitchEnable.performed -= instance.OnSwitchEnable;
            @SwitchEnable.canceled -= instance.OnSwitchEnable;
        }

        public void RemoveCallbacks(IWindowActions instance)
        {
            if (m_Wrapper.m_WindowActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWindowActions instance)
        {
            foreach (var item in m_Wrapper.m_WindowActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WindowActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WindowActions @Window => new WindowActions(this);
    public interface IWindowActions
    {
        void OnSwitchEnable(InputAction.CallbackContext context);
    }
}
